### ISSUE TITLE
addition to week 6, on your own section

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#11]
How to file a FOIA request, <a href="http://www.yaleisp.org/media-freedom-and-information-access-clinic">Media Freedom and Information Access Clinic, Yale Law School</a>,TBD

**Comment by luisdaniel** [comment]
What's with the TBD?

**Comment by nikzei** [comment]
To be determined = it's in ideation phase...

**Comment by luisdaniel** [comment]
haha I know what TBD means, I mean what am I doing with it? Do you just want me to add it at the end of "Yale, Law School, TBD"?

**Comment by nikzei** [comment]
Yes - is that weird?
We might have some multimedia content for students from Yale but it's not confirmed yet. This came from Beth; I think it looks ok . . . 
Let's go with it for now, unless you think something else would work better?

**Comment by luisdaniel** [comment]
I guess if it reads "Read X blog post, TBD" I'd be like... "what's to be determined?"

Anyway, added the link.... if you guys really want a TBD on there... then I guess I can add it.

**Comment by nikzei** [comment]
Thanks, Luis. 
The X is TBD. The idea is that it read more like, "Read a blogpost about acronyms by <a href="http://thegovlab.org/about/team/luis-daniel/">Luis</a>, TBD"
Otherwise, it's like "read a blogpost about some subject matter by this guy, here's his bio." 
I'd be like, what am I supposed to read? Which blogpost specifically?
Make sense?

**Comment by luisdaniel** [comment]
I thought the X was "How to file a FOIA request, Media Freedom and Information Access Clinic, Yale Law School". Isn't it?

**Comment by nikzei** [comment]
I'm going to write an essay about this topic later tonight and will share with you after it's been revised and edited.
But for the meantime, I think that hat you did was right - leave is and forget what I just wrote
:)

**Comment by luisdaniel** [comment]
lol ok.
