### ISSUE TITLE
adding two more videos

### ISSUE THREAD

**Issue by celiahannon** [GovLab/academy-courses#17]
@luisdaniel @claudioccm 
please could we add two more videos onto the syllabus?

Alph's video for Week 1 on defining a problem 
Embedded into 
"Watch Defining Your Problem with Dr. Alpheus Bingham, Founder, Innocentive".
https://drive.google.com/file/d/0B-wKfs-gjfyedFJBWVVreUFudm8/edit?usp=sharing

this additional video for 
WEEK 0 (Prior to Start)
embedded in this new text after Beth's course intro video:
'Nicholas Fusso of the D-Prize invites your to apply to their next seed capital competition. Watch.'
https://drive.google.com/file/d/0B-wKfs-gjfyeYllNOUozNThjNTQ/edit?usp=sharing

**Comment by luisdaniel** [comment]
You need to upload those videos to either youtube or vimeo (check [what we use](http://thegovlab.org/media-library/)). whichever platform we are using. then send me the links, and I'll post them on the syllabus.

**Comment by celiahannon** [comment]
I don't have access to any of those accounts. There's nobody in the office. Thoughts?

**Comment by luisdaniel** [comment]
Any luck on this? 

I can add links to the videos on the google drive if need be.

**Comment by nikzei** [comment]
Sorry Luis - we've been pretty overwhelmed and haven't gotten to it yet. I have the Vimeo account info that you sent but it'll take a little bit of time to upload since Vimeo tends to be slow. If you are able to do this, that would be great.

Also, an fyi, we have:
- intro audio files from Beth that she wants to add to the syllabus (I have one for the first few weeks of class)
- we also have the "meet the academy team" intro video that beth wants on the syllabus. I will send you access to the file. I can make a decision about where it should go once I finish up a few things. But it's not an emergency - we can do it on Tuesday

**Comment by luisdaniel** [comment]
I'm in Mexico. Supposed to be vacation, but who are we kidding.

Can't meet in person, so when you need a change, just let me know what you need (try to be as specific as you can, I'm slow).

**Comment by nikzei** [comment]
Beth instructed us to think of you as "working." 
lol?

My position is that these multimedia additions to the syllabus can be dealt with early next week with little consequence, but that's just me.

**Comment by luisdaniel** [comment]
just linked to the files on the drive. Closing issue. 

I also have audio files, please let me know where you want to link them. Submit separate issue for those.

**Comment by celiahannon** [comment]
Nikki - can you check these are the right versions please? I don't know
whether you or Danya were working on ones with academy bumpers.

the Giff Constable video and the intro video to the govlab team is not up
either - nikki I believe you have the link to these on vimeo? could you
share with Luis?

On Tue, Sep 2, 2014 at 6:07 PM, Luis notifications@github.com wrote:

> just linked to the files on the drive. Closing issue.
> 
> I also have audio files, please let me know where you want to link them.
> Submit separate issue for those.
> 
> —
> Reply to this email directly or view it on GitHub
> http://t.signauxtrois.com/link?url=https%3A%2F%2Fgithub.com%2FGovLab%2Fgovlab.github.io%2Fissues%2F17%23issuecomment-54225288&ukey=agxzfnNpZ25hbHNjcnhyGAsSC1VzZXJQcm9maWxlGICAwPG9vJQJDA&k=2b99b000-aceb-4b63-d080-e47718e2f01c
> .

**Comment by luisdaniel** [comment]
not sure I see an issue with a giff constable link

**Comment by celiahannon** [comment]
Where it says:

'Talking to Humans (Video)' it should link to Giff's video which Danya has
been working on.

I know Nikki is overwhelmed with work (and I'm not up to date having left
already) so, Luis, it may shorten the timescales if you connect with Danya
about any pending videos which need to be uploaded and which are finished.
She's been storing them on vimeo I believe.

danya.abt@gmail.com

Nikki can advise as to where things should go.

Over and out.

**Comment by nikzei** [comment]
Luis has Danya's Vimeo link with the password so all the updated info is taken care of.
Apologies in advance if I'm not responsive - there's a lot going on right now.
Thanks again for helping to keep us on track!

**Comment by luisdaniel** [comment]
Lots going on here too. Have to prep a website to present to Mexican president's office on thursday so

I don't recall getting a link for giff's video. can someone just paste it here? why does a link have a password?
