### ISSUE TITLE
Update week 5

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#20]
Title: One-on-one project check-in sessions - WE WILL NOT MEET DURING CLASS TIME.

We are holding one-on-one mentoring sessions instead of class. We'll be at the GovLab in Brooklyn for those who want to meet with us in person. For those who cannot meet in Brooklyn,we'll be available for online google hangouts. Please keep in mind that if you are working as part of a team, please try your best to schedule a meeting that the whole team can attend.

The link where you can schedule is here calendly.com/luis--3. Please schedule by Sunday so we can prepare for your meetings with you.

We understand that we've given a lot of content for you to review over the past few weeks. Our hope is that this week will give you more space to review more, reflect, and apply to the projects that you are developing.

**Comment by luisdaniel** [comment]
done.
