### ISSUE TITLE
Maria's Bio

### ISSUE THREAD

**Issue by mphermosilla** [GovLab/academy-courses#21]
Maria Hermosilla is studying a Master of Public Administration at NYU. Before moving to the USA from Santiago, Chile, she worked for five years in the public and nonprofit sectors. During the last two she led the citizen relations and information management unit at the Ministry of Public Works, where she implemented open government projects. Prior to that, she was chief of staff of the Vice Minister of Energy. Maria is a journalist with 4 years of experience in television as a reporter, producer and assistant director, and freelance correspondent for NPR. She can be found on twitter at @mphermosilla.

**Comment by luisdaniel** [comment]
done.
