### ISSUE TITLE
Week 6:

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#23]
This week we will be IN CLASS discussing researching with Stefaan Verhulst and Andrew Young, both researchers at the GovLab.

The slide deck that they will be using is attached here. If you have five minutes before class, please sign up for Coggle (http://coggle.it), watch the tutorial video on the page and take a few minutes to replicate the three mindmap templates in the deck.

Next week we will meet during regular class hours but ONLINE during which we'll be discussing working with institutions.

[PDF slide deck in Andrew's email attached]

**Comment by luisdaniel** [comment]
done.
