### ISSUE TITLE
List Online or In person for each remaining week 

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#24]
WEEK 5 (Oct 7-8) - in class
WEEK 7 (Oct 15-16) - online
WEEK 7 (October 22-23) - online 
WEEK 8 (October 29-30) - in class 
WEEK 9 (November 5-6) - online 
WEEK 10 (Nov 12-13) - in class 
WEEK 11 (November 19-20) - online 
WEEK 12 - (December 3-4) No in class or online sessions; work on projects - do individuals consultations 
WEEK 13 - (December 10-11) - Demo Day! In person for MIT and NYU students, online for the rest

**Comment by luisdaniel** [comment]
done
