### ISSUE TITLE
ADD FAQ ITEM - Is this  12, 13 or 14 week program?

### ISSUE THREAD

**Issue by luisdaniel** [GovLab/academy-courses#3]
ADD FAQ ITEM - Is this  12, 13 or 14 week program?

We recognize that different institutions use different calendars (e.g. ITP is 12 weeks and Poly is 14 weeks). We will work with you to adjust the program accordingly. Please keep in mind that the Demo Day to funders and guests will likely be during Week 14.

**Comment by luisdaniel** [comment]
Added.

**Comment by sahuguet** [comment]
Can you send a link with the changes.

**Comment by sahuguet** [comment]
![banksy](https://cloud.githubusercontent.com/assets/355907/3898133/b3e428c4-2268-11e4-98f1-169583202187.jpg)

**Comment by luisdaniel** [comment]
You mean this?

https://github.com/GovLab/govlab.github.io/commit/d19c27d12a304a97941cf75780c18e03d6658f28

**Comment by sahuguet** [comment]
I meant the live version of the changes, if it is available somewhere.

On Tue, Aug 12, 2014 at 5:36 PM, Luis notifications@github.com wrote:

> You mean this?
> 
> d19c27d
> https://github.com/GovLab/govlab.github.io/commit/d19c27d12a304a97941cf75780c18e03d6658f28
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/govlab.github.io/issues/3#issuecomment-51981201
> .

## 

Arnaud Sahuguet
Do a little. Change a lot. http://www.google.com/onetoday

**Comment by luisdaniel** [comment]
http://govlab.github.io/academy-courses/Solving-Public-Problems-Fall-2014/
