### ISSUE TITLE
update to prerequisites section

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#7]
@luisdaniel Beth wants to make the following change to the prerequisites section:
replace content following second bullet ( "a 1-2 page description . . ." (or however this has been rephrased in newer drafts)) with "completion of our online informational questionnaire"

"online informational questionnaire" should hyperlink to the form: https://docs.google.com/forms/d/1AYDCLwXqxGRRMEMnmQVKKpXhoXNnnpN-wBQi2jGwd_8/viewform?c=0&w=1)

**Comment by luisdaniel** [comment]
I need clarification.  
There are four more bullets after "A 1-2 page description". Do you want me to _delete_ those four, and just add one that says "Completion of our ~~online~~ informational questionnaire"?

**Comment by luisdaniel** [comment]
Got clarification from Beth. 
Check the changes and let me know if you need something else changed.

**Comment by nikzei** [comment]
Looks good-
