### ISSUE TITLE
change: Participant Badges section

### ISSUE THREAD

**Issue by nikzei** [GovLab/academy-courses#8]
when you google "merit badges," all that comes up is boy scout/eagle scout stuff . . . it's the wrong term.

Please replace w/ "digital badges"  - Beth agreed by email so it should be ready for update.

and that the term be hyperlinked so people can easily learn what we mean by this. Here's a good hyperlink: http://www.macfound.org/programs/digital-badges/

Thanks!

**Comment by luisdaniel** [comment]
I might be spoiling you guys getting these done so quickly. Might need to scale back a bit (at least so I  don't have to stop what I'm doing every time to make these changes).  

done.
